"""Migracao inicial MySQL

Revision ID: 1131bdeabf71
Revises: 
Create Date: 2026-04-11 18:55:26.268115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1131bdeabf71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('remedios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('dosagem', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hora_prevista', sa.Time(), nullable=False),
    sa.Column('remedio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['remedio_id'], ['remedios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_diarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.Date(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_diarios')
    op.drop_table('horarios')
    op.drop_table('remedios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
